# Generated by Django 3.2.25 on 2024-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_snapshot_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
