# Generated by Django 3.2.25 on 2024-07-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_map_snapshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_snapshot_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
