# Generated by Django 3.2.25 on 2024-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('buddy', models.CharField(max_length=255)),
                ('depth', models.FloatField()),
                ('temp', models.FloatField()),
                ('visibility', models.FloatField()),
                ('bottom_time', models.FloatField()),
            ],
        ),
    ]
