# Generated by Django 3.2.25 on 2024-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dives', '0002_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dive',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='divelog',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
