# Generated by Django 3.2.25 on 2024-07-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dives', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='map_snapshot_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
